# 1. Shape

## 1차원 배열의 생성
- a.shape는 배열의 크기를 확인할때 사용한다

In [1]:
import numpy as np
a = np.array([1, 2, 3]) 
print(a.shape) 

(3,)


## 2차원 배열의 생성

In [2]:
b = np.array([[1,2,3],[4,5,6]]) 
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## 3차원 배열의 생성
(layer, row, column)


In [3]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
print(c)
print(c.shape) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


## Layer 만들기

In [4]:
d = np.array([
    [
        [1,2],
        [3,4]
    ]
])
print(d.shape) #(1,2,2) because layer is 1

e = np.array([
        [1,2],
        [3,4]
])
print(e.shape) #(2,2)

(1, 2, 2)
(2, 2)


# 2. 배열의 병합과 분리

## 배열 병합 
- Concatenate

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a,b)) #[1,2,3,4,5,6]
print(c)

[1 2 3 4 5 6]


## 배열 분리
- 분리할 배열과 분리할 인덱스를 지정, axis는 차원을 지정한다

In [6]:
d = np.array([[1,2,3],[4,5,6]])
#분리할 배열과 분리할 인덱스를 지정, axis는 차원을 지정함
e, f = np.split(d,[1],axis=0)
print(e)
print(f)

[[1 2 3]]
[[4 5 6]]


# 3. 배열 연산

- 원소별 덧셈 (+)

- 원소별 곱셈 (*)

Method 이용

- 모든 원소의 합 : sum

- 모든 원소의 평균 : mean

- 최솟값 : min

- 최댓값 : max

- 배열의 누적합 : cumsum

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b # [5,7,9] #원소별 덧셈
print(c)

d = a*b #[4,10,18] a의 원소와 b의 원소를 곱함
print(d)

e = a + 1 #[2,3,4] 원소에 1씩 더함
print(e)

#method 이용

a1 = np.array([1,2,3])

b1 = np.sum(a1) #a의 모든 원소의 합
print(b1)

c1 = np.mean(a1) #모든 원소의 평균
print(c1)

d1 = min(a1) #최솟값
print(d1)

e1 = max(a1) #최댓값
print(e1)

f1 = np.cumsum(a1)# 배열의 누적합
print(f1) 

[5 7 9]
[ 4 10 18]
[2 3 4]
6
2.0
1
3
[1 3 6]


## 2,3차원에서의 연산 

In [20]:
b2D = np.array([[1,2,3],[4,5,6]])
c2D = np.array([[4,5,6],[1,2,3]])
print(b2D+c2D)

[[5 7 9]
 [5 7 9]]


# 4. 배열 형태 변경

Using reshape

In [21]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)

#배열의 형태를 변경한다
b = a.reshape((2,3)) #배열을 바꾸고 숫자를 처음부터 넣어줌?
print(b)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]


## 배열 전치 (A^T)
Using .T

In [32]:
c = a.T
print(c)
print(c.shape) #(2,3)

[1 2 3 4 5]
(5,)


# 5. 인덱싱 및 슬라이싱

In [31]:
a = np.array([1,2,3,4,5])

## 인덱싱

In [30]:
b = a[0] #1
c = a[2] #3

## 슬라이싱

In [29]:
d = a[1:4] #[2,3,4]
e = a[:3] #[1,2,3]
f = a[3:] #[4,5]
print(b)
print(c)
print(d)
print(e)
print(f)

1
6
[2 3]
[1 2 3]
[]


## 다차원 배열에서의 인덱싱과 슬라이싱

### 2차원

In [27]:
a1 = np.array([[1,2,3],[4,5,6]])

b = a1[0,0] #0번째 배열의 0번째 =>1
c = a1[1,2] #1번째 배열의 2번째 =>6
d = a1[0, 1:3] #[2,3]
e = a1[:,1] #[2,5] 전체에서 1번만 슬라이싱
f = a1[:,:2] #[[1,2],[4,5]] 전체에서 1번까지 슬라이싱

### 3차원

In [28]:
a2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a2[0,0]) #[1,2,3]
print(a2[0,1,1]) #5
print(a2[:,1,1]) #[5,11]

[1 2 3]
5
[ 5 11]


# 6. 주요 함수

## 모든 원소가 0인 배열을 생성 
np.zeros()

In [24]:
arr = np.zeros((2,3)) #크기가 2x3인 배열을 생성
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## 모든 원소가 1인 배열을 생성
np.ones()

In [ ]:
arr2 = np.ones((2,4)) # 크기가 2x4인 배열을 생성
print(arr2)

## 원하는 갯수의 배열을 생성
np.linspace(a,b,c) =>  a부터 b까지 균등한 간격으로 c개 출력

In [ ]:
arr4 = np.linspace(0,1,5) 
print(arr4)

## 0부터 1까지의 random 숫자를 생성하여 배열을 만든다
Using np.random.random()

In [ ]:
arr5 = np.random.random((3,3)) #3x3 배열의 random한 아이를 만든다
print(arr5)

## 평균이 0이고 표준편차가 1인 정규분포를 따르는 random숫자들을 생성하여 배열을 만든다
Using np.random.randn()

In [ ]:
arr6 = np.random.randn(2,4)
print(arr6)